// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNYYW2N2BFtF88ihkQrcwjiWS8gZtzVsU',
    appId: '1:970346398053:web:d529481f1cb61f4af5618c',
    messagingSenderId: '970346398053',
    projectId: 'flutter-38e62',
    authDomain: 'flutter-38e62.firebaseapp.com',
    storageBucket: 'flutter-38e62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcuFd2P5j82R_vxbJ5rZ0QsmKS3JhFAJ8',
    appId: '1:970346398053:android:c83f5e4b61600e06f5618c',
    messagingSenderId: '970346398053',
    projectId: 'flutter-38e62',
    storageBucket: 'flutter-38e62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdaNcEWrkV_iCi8zG7svSItlMjfPKfXKc',
    appId: '1:970346398053:ios:c4ad944443a1be08f5618c',
    messagingSenderId: '970346398053',
    projectId: 'flutter-38e62',
    storageBucket: 'flutter-38e62.appspot.com',
    iosBundleId: 'com.example.flutterProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdaNcEWrkV_iCi8zG7svSItlMjfPKfXKc',
    appId: '1:970346398053:ios:0f783309b6c4bda7f5618c',
    messagingSenderId: '970346398053',
    projectId: 'flutter-38e62',
    storageBucket: 'flutter-38e62.appspot.com',
    iosBundleId: 'com.example.flutterProje.RunnerTests',
  );
}
